version: '3.8'
services:
  bigdata_app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
