services:
  bigdata_app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - /var/run/docker.sock:/var/run/docker.sock  # 👈 Monte la socket Docker
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
