# backend/docker/mongodb/Dockerfile

FROM mongo:latest

# Exposer le port MongoDB par défaut
EXPOSE 27017

# Ici tu peux copier un script d'initialisation Mongo si besoin, sinon laisse vide
# COPY init-mongo.js /docker-entrypoint-initdb.d/

# Pas besoin de redéfinir CMD, l'image officielle le fait déjà très bien
